fastaDir: '/home/afollette/PycharmProjects/pdx_Annotater/vepDBs/homo_sapiens/Homo_sapiens.GRCh38.dna.primary_assembly.fa'
alleleDB: '/home/afollette/PycharmProjects/pdx_Annotater/vepDBs/homo_sapiens_vep_98_GRCh38'
vepSingularityImage: '/home/afollette/PycharmProjects/pdx_Annotater/pdx-liftover-vep_release98.3.simg'
vepArguments:
  - --verbose
  - --vcf #write output to VCF format
  - --force #Forces overwrite of existing output
  - --check_existing #Checks for existing variants in co-location
  - --check_ref #Checks reference against Ensembl database. Skips if not matching
  - --merged #Get Refseq and Ensembl lookup databases
  - --use_given_ref # Overrides BAM assorted RefSeq
  - --offline
  - --symbol
  - --polyphen s
  - --sift s
  - --hgvs
  - --hgvsg
  - --variant_class
  - --canonical