fastaDir: '/Users/tushar/pdx/mutation-annotater/vepDB/homo_sapiens/Homo_sapiens.GRCh38.dna.primary_assembly.fa'
alleleDB: '/Users/tushar/pdx/mutation-annotater/vepDB/homo_sapiens_vep_98_GRCh38'
vepSingularityImage: 'pdx-liftover_vep_release98.3.sif'
vepArguments:
  - --verbose
  - --vcf # Format output in VCF
  - --force #Forces overwrite of existing output
  - --check_existing #Checks for existing variants in co-location
  - --check_ref #Checks reference against Ensembl database. Skips if not matching
  - --use_given_ref # Overrides BAM assorted RefSeq
  - --symbol
  - --polyphen s
  - --sift s
  - --hgvs
  - --variant_class
  - --no_stats #Turned off stats
  - --pick --pick_order biotype,canonical,appris,tsl,ccds,rank,length,mane # PDX Finder personal preference order